### ISSUE TITLE
NullReferenceException when trying to open the tool in Unity 2020.2: AssetStoreClient.get_ActiveSessionID 

### ISSUE THREAD

**Issue by zwcloud** [zwcloud/AssetStoreTools#7]
It happens with latest version of official asset store tools:
https://forum.unity.com/threads/issue-asset-store-tools-not-working-in-2020-2.1023478

> NullReferenceException: Object reference not set to an instance of an object
AssetStoreClient.get_ActiveSessionID () (at <f111d93001994aac9709759ecfbdde58>:0)
AssetStoreClient.get_HasActiveSessionID () (at <f111d93001994aac9709759ecfbdde58>:0)
LoginWindow.get_IsLoggedIn () (at <f111d93001994aac9709759ecfbdde58>:0)
AssetStoreManager.ValidateAssetStoreLogout () (at <f111d93001994aac9709759ecfbdde58>:0)

Existing lastest release for Unity 2020.1 doesn't work on 2020.2 either. Further investigation on this issue needed.

**Comment by PatHightree** [comment]
This issue also occurs with the official asset store tools (Unity 2020.2.0f1).

**Comment by lucasmontec** [comment]
Also occurs with me!

**Comment by zwcloud** [comment]
I have fixed this but not tested if uploading works. Just wait a few days.

**Comment by zwcloud** [comment]
I have uploaded my packages with it:
![image](https://user-images.githubusercontent.com/6965758/113732333-16b13700-972c-11eb-8f5b-9ff962f9bdda.png)
